name: causal-confusion
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.0=py36_0
  - astor=0.8.0=py36_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py36_0
  - cffi=1.13.0=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - cupti=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.3.2=py_0
  - google-pasta=0.1.7=py_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - ignite=0.2.1=py36_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - markdown=3.1.1=py36_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - mpi4py=2.0.0=py36_2
  - mpich2=1.4.1p1=0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.17.2=py36haad9e8e_0
  - numpy-base=1.17.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1d=h7b6447c_3
  - pillow=6.2.0=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - protobuf=3.9.2=py36he6710b0_0
  - pycparser=2.19=py36_0
  - python=3.6.9=h265db76_0
  - pytorch=1.0.1=py3.6_cuda10.0.130_cudnn7.4.2_2
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.21.3=py36hd81dba3_0
  - scipy=1.3.1=py36h7c811a0_0
  - setuptools=41.4.0=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=1.14.0=py36hf484d3e_0
  - tensorflow=1.14.0=gpu_py36h57aa796_0
  - tensorflow-base=1.14.0=gpu_py36h8d69cac_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.2=py_3
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - "git+https://github.com/pimdh/baselines@no-mujoco"
    - click==7.0
    - cloudpickle==1.2.2
    - dill==0.3.1.1
    - future==0.18.1
    - gym==0.15.3
    - joblib==0.14.0
    - opencv-python==4.1.1.26
    - progressbar2==3.47.0
    - pyglet==1.3.2
    - python-utils==2.3.0
    - tqdm==4.36.1

